version: "3"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04
    environment:
      - SA_PASSWORD=password
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433

  app:
    build: .
  